-- SPD数据库 - HIS门诊收费明细表
CREATE TABLE IF NOT EXISTS `his_mz_sfmx` (
  `outpatient_charge_id` BIGINT(20) NOT NULL COMMENT '门诊收费ID',
  `patient_id` INT(11) DEFAULT NULL COMMENT '患者ID',
  `patient_name` VARCHAR(100) DEFAULT NULL COMMENT '患者姓名',
  `outpatient_no` VARCHAR(50) DEFAULT NULL COMMENT '门诊号',
  `clinic_code` VARCHAR(50) DEFAULT NULL COMMENT '科室编码',
  `clinic_name` VARCHAR(200) DEFAULT NULL COMMENT '科室名称',
  `doctor_id` VARCHAR(50) DEFAULT NULL COMMENT '医生ID',
  `doctor_name` VARCHAR(100) DEFAULT NULL COMMENT '医生姓名',
  `charge_item_id` VARCHAR(50) DEFAULT NULL COMMENT '收费项目ID',
  `item_name` VARCHAR(500) DEFAULT NULL COMMENT '项目名称',
  `spec_model` VARCHAR(500) DEFAULT NULL COMMENT '规格型号',
  `batch_no` VARCHAR(100) DEFAULT NULL COMMENT '批次号',
  `expire_date` DATETIME DEFAULT NULL COMMENT '有效期',
  `charge_date` DATETIME DEFAULT NULL COMMENT '收费日期',
  `quantity` DECIMAL(18, 2) DEFAULT NULL COMMENT '数量',
  `unit_price` DECIMAL(18, 4) DEFAULT NULL COMMENT '单价',
  `total_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT '总金额',
  `charge_operator` VARCHAR(100) DEFAULT NULL COMMENT '收费操作员',
  `payment_type` VARCHAR(50) DEFAULT NULL COMMENT '支付方式',
  `receipt_no` VARCHAR(100) DEFAULT NULL COMMENT '收据号',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`outpatient_charge_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_outpatient_no` (`outpatient_no`),
  KEY `idx_charge_date` (`charge_date`),
  KEY `idx_charge_item_id` (`charge_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='HIS门诊收费明细表';
