-- =============================================================================
-- 众阳云健康 HIS 接口镜像表 — 手工建表脚本（SPD 业务库，如 aspt）
-- =============================================================================
-- 【非标准对象】众阳云健康（msun）专用镜像表，与其他 HIS 厂家镜像表区分；勿纳入标准库初始化。
-- 新客户部署：标准库初始化完成后，可按对接需要选择性执行本脚本；不需要时可删除全部 m_* 表。
-- 表前缀：m_（mirror）
-- 接口覆盖：2.1.9 / 2.1.12 / 2.5.44 / 2.5.58 / 2.5.62 / 2.5.63 / 2.5.102
-- 执行前请先 USE 目标 SPD 业务库，按「/」分段执行；可按需只建部分表。
-- =============================================================================

-- USE `aspt`;
/

-- 同步批次日志（手工/定时导入均可登记）
CREATE TABLE IF NOT EXISTS `m_sync_batch` (
  `batch_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `sync_batch_no` VARCHAR(64) NOT NULL COMMENT '批次号',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境 prod/test',
  `api_code` VARCHAR(32) DEFAULT NULL COMMENT '接口编号，空表示多接口批次',
  `mirror_source` VARCHAR(32) NOT NULL DEFAULT 'manual_probe' COMMENT '来源 manual_probe/scheduled',
  `record_count` INT DEFAULT 0 COMMENT '本批次写入行数',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`batch_id`),
  UNIQUE KEY `uk_batch_no` (`sync_batch_no`),
  KEY `idx_hospital_env` (`hospital_key`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-同步批次';
/

-- 2.1.9 科室基本信息
CREATE TABLE IF NOT EXISTS `m_dept` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.1.9' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `dept_id` VARCHAR(64) NOT NULL COMMENT '科室ID',
  `dept_code` VARCHAR(64) DEFAULT NULL COMMENT '科室编码',
  `dept_name` VARCHAR(200) DEFAULT NULL COMMENT '科室名称',
  `category_id` VARCHAR(64) DEFAULT NULL COMMENT '主分类ID',
  `invalid_flag` VARCHAR(32) DEFAULT NULL COMMENT '作废标志',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `alias_name` VARCHAR(200) DEFAULT NULL COMMENT '别名',
  `input_code` VARCHAR(64) DEFAULT NULL COMMENT '拼音码',
  `input_alias_code` VARCHAR(64) DEFAULT NULL COMMENT '别名拼音码',
  `full_code` VARCHAR(128) DEFAULT NULL COMMENT '全拼',
  `full_alias_code` VARCHAR(128) DEFAULT NULL COMMENT '别名全拼',
  `wb_code` VARCHAR(64) DEFAULT NULL COMMENT '五笔码',
  `register_flag` VARCHAR(16) DEFAULT NULL COMMENT '挂号标志',
  `level` INT DEFAULT NULL COMMENT '层级',
  `sort_order` INT DEFAULT NULL COMMENT '排序',
  `start_time` VARCHAR(32) DEFAULT NULL COMMENT '开始时间',
  `end_time` VARCHAR(32) DEFAULT NULL COMMENT '结束时间',
  `parent_id` VARCHAR(64) DEFAULT NULL COMMENT '上级科室ID',
  `room_address` VARCHAR(500) DEFAULT NULL COMMENT '房间地址',
  `msun_org_id` VARCHAR(64) DEFAULT NULL COMMENT '众阳机构ID',
  `account_dept_id` VARCHAR(64) DEFAULT NULL COMMENT '核算科室ID',
  `national_dept_insurance_code` VARCHAR(64) DEFAULT NULL COMMENT '国家医保科室编码',
  `introduction` TEXT COMMENT '简介',
  `dept_classify_id` VARCHAR(64) DEFAULT NULL COMMENT '科室分类ID',
  `hospital_area_id` VARCHAR(64) DEFAULT NULL COMMENT '院区ID',
  `phone` VARCHAR(64) DEFAULT NULL COMMENT '电话',
  `emerg_phone` VARCHAR(64) DEFAULT NULL COMMENT '急诊电话',
  `his_org_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS机构ID',
  `his_creater_id` VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',
  `his_creater_name` VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  `his_create_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS创建时间',
  `his_updater_id` VARCHAR(64) DEFAULT NULL COMMENT '更新人ID',
  `his_update_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS更新时间',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_dept` (`dept_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_dept_code` (`dept_code`),
  KEY `idx_dept_name` (`dept_name`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.1.9科室基本信息';
/

CREATE TABLE IF NOT EXISTS `m_dept_category_rel` (
  `rel_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `dept_id` VARCHAR(64) NOT NULL COMMENT '科室ID',
  `category_id` VARCHAR(64) NOT NULL COMMENT '分类ID(categoryIdList)',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`rel_id`),
  UNIQUE KEY `uk_dept_cat` (`dept_id`, `category_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-科室分类关联(categoryIdList)';
/

-- 2.1.12 用户身份信息
CREATE TABLE IF NOT EXISTS `m_user_identity` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.1.12' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `identity_id` VARCHAR(64) NOT NULL COMMENT '身份ID',
  `dept_id` VARCHAR(64) DEFAULT NULL COMMENT '科室ID',
  `dept_code` VARCHAR(64) DEFAULT NULL COMMENT '科室编码',
  `dept_name` VARCHAR(200) DEFAULT NULL COMMENT '科室名称',
  `user_id` VARCHAR(64) DEFAULT NULL COMMENT '用户ID',
  `user_name` VARCHAR(128) DEFAULT NULL COMMENT '用户姓名',
  `role_id` VARCHAR(64) DEFAULT NULL COMMENT '角色ID',
  `role_name` VARCHAR(128) DEFAULT NULL COMMENT '角色名称',
  `user_code` VARCHAR(64) DEFAULT NULL COMMENT '用户编码',
  `staff_code` VARCHAR(64) DEFAULT NULL COMMENT '工号',
  `role_type` VARCHAR(16) DEFAULT NULL COMMENT '角色类型',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_identity` (`identity_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.1.12用户身份信息';
/

CREATE TABLE IF NOT EXISTS `m_user_identity_account` (
  `rel_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `identity_id` VARCHAR(64) NOT NULL COMMENT '身份ID',
  `account_no` VARCHAR(128) NOT NULL COMMENT '账号(accountList)',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`rel_id`),
  UNIQUE KEY `uk_identity_account` (`identity_id`, `account_no`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-用户身份账号(accountList)';
/

-- 2.5.44 药品、材料字典
CREATE TABLE IF NOT EXISTS `m_drug_dict` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.44' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `drug_id` VARCHAR(64) NOT NULL COMMENT '药品/材料ID',
  `drug_spec_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '众阳HIS产品档案唯一键（同步至fd_material.his_spec_packing_id）',
  `drug_name` VARCHAR(500) DEFAULT NULL COMMENT '名称',
  `spec` VARCHAR(500) DEFAULT NULL COMMENT '规格',
  `min_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '最小包装ID',
  `min_packing_name` VARCHAR(64) DEFAULT NULL COMMENT '最小包装单位',
  `max_packing_name` VARCHAR(64) DEFAULT NULL COMMENT '最大包装单位',
  `min_dose` DECIMAL(18,6) DEFAULT NULL COMMENT '最小剂量',
  `dose_unit_id` VARCHAR(64) DEFAULT NULL COMMENT '剂量单位ID',
  `dose_unit_name` VARCHAR(64) DEFAULT NULL COMMENT '剂量单位',
  `dosage_form_id` VARCHAR(64) DEFAULT NULL COMMENT '剂型ID',
  `dosage_form_name` VARCHAR(128) DEFAULT NULL COMMENT '剂型',
  `input_code` VARCHAR(128) DEFAULT NULL COMMENT '拼音码',
  `full_code` VARCHAR(256) DEFAULT NULL COMMENT '全拼',
  `approved_no` VARCHAR(128) DEFAULT NULL COMMENT '批准文号',
  `produce_id` VARCHAR(64) DEFAULT NULL COMMENT '生产厂商ID',
  `produce_name` VARCHAR(500) DEFAULT NULL COMMENT '生产厂商',
  `drug_catagory_id` VARCHAR(64) DEFAULT NULL COMMENT '分类ID',
  `drug_catagory_name` VARCHAR(128) DEFAULT NULL COMMENT '分类名称',
  `national_medical_insurance_code` VARCHAR(128) DEFAULT NULL COMMENT '国家医保编码',
  `min_dose_count` DECIMAL(18,6) DEFAULT NULL COMMENT '最小剂量数',
  `type_name` VARCHAR(500) DEFAULT NULL COMMENT '药品类型描述',
  `drug_code` VARCHAR(128) DEFAULT NULL COMMENT '药品编码',
  `attention_points` TEXT COMMENT '注意事项',
  `indication` TEXT COMMENT '适应症',
  `retail_price` DECIMAL(18,4) DEFAULT NULL COMMENT '零售价',
  `buy_price` DECIMAL(18,4) DEFAULT NULL COMMENT '进价',
  `invalid_flag` VARCHAR(32) DEFAULT NULL COMMENT '作废标志',
  `memo` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `winning_bid_code` VARCHAR(128) DEFAULT NULL COMMENT '中标编码',
  `license_number` VARCHAR(128) DEFAULT NULL COMMENT '许可证号',
  `model_type` VARCHAR(256) DEFAULT NULL COMMENT '型号',
  `purchase_attribute_id` VARCHAR(64) DEFAULT NULL COMMENT '采购属性ID',
  `purchase_attribute_name` VARCHAR(128) DEFAULT NULL COMMENT '采购属性',
  `material_monitor_flag` VARCHAR(16) DEFAULT NULL COMMENT '耗材监控标志',
  `antibiotics_level_id` VARCHAR(64) DEFAULT NULL COMMENT '抗生素级别ID',
  `antibiotics_level_name` VARCHAR(128) DEFAULT NULL COMMENT '抗生素级别',
  `antibiotics_type_id` VARCHAR(64) DEFAULT NULL COMMENT '抗生素类型ID',
  `antibiotics_type_name` VARCHAR(128) DEFAULT NULL COMMENT '抗生素类型',
  `local_medical_insurance_code` VARCHAR(128) DEFAULT NULL COMMENT '地方医保编码',
  `dict_drug_pharmacology_category_code_list` TEXT COMMENT '药理分类编码列表JSON',
  `dict_drug_pharmacology_category_id_list` TEXT COMMENT '药理分类ID列表JSON',
  `dict_drug_pharmacology_category_name_list` TEXT COMMENT '药理分类名称列表JSON',
  `essential_drug_name` VARCHAR(128) DEFAULT NULL COMMENT '基本药物名称',
  `essential_drug_id` VARCHAR(64) DEFAULT NULL COMMENT '基本药物ID',
  `solvent_flag` VARCHAR(16) DEFAULT NULL COMMENT '溶媒标志',
  `usage_type_id` VARCHAR(64) DEFAULT NULL COMMENT '用法类型ID',
  `usage_type_name` VARCHAR(128) DEFAULT NULL COMMENT '用法类型',
  `antibiotics_flag` VARCHAR(16) DEFAULT NULL COMMENT '抗生素标志',
  `ddd` VARCHAR(32) DEFAULT NULL COMMENT 'DDD',
  `ddd_packing_name` VARCHAR(64) DEFAULT NULL COMMENT 'DDD包装单位',
  `blood_flag` VARCHAR(16) DEFAULT NULL COMMENT '血液制品标志',
  `china_drug_injection_flag` VARCHAR(16) DEFAULT NULL COMMENT '中药注射剂标志',
  `min_spec` VARCHAR(256) DEFAULT NULL COMMENT '最小规格',
  `antitumor_flag` VARCHAR(16) DEFAULT NULL COMMENT '抗肿瘤标志',
  `antitumor_level_id` VARCHAR(64) DEFAULT NULL COMMENT '抗肿瘤级别ID',
  `antitumor_level_name` VARCHAR(128) DEFAULT NULL COMMENT '抗肿瘤级别',
  `high_risk_flag` VARCHAR(16) DEFAULT NULL COMMENT '高危标志',
  `high_warning_level` VARCHAR(64) DEFAULT NULL COMMENT '高警示级别',
  `high_warning_memo` VARCHAR(500) DEFAULT NULL COMMENT '高警示说明',
  `supplier_id` VARCHAR(64) DEFAULT NULL COMMENT '供应商ID',
  `supplier_name` VARCHAR(500) DEFAULT NULL COMMENT '供应商',
  `invoice_id` VARCHAR(64) DEFAULT NULL COMMENT '发票分类ID',
  `invoice_name` VARCHAR(128) DEFAULT NULL COMMENT '发票分类',
  `med_insurance_category` VARCHAR(32) DEFAULT NULL COMMENT '医保类别',
  `med_insurance_category_name` VARCHAR(128) DEFAULT NULL COMMENT '医保类别名称',
  `min_dose_unit_id` VARCHAR(64) DEFAULT NULL COMMENT '最小剂量单位ID',
  `material_or_drug` VARCHAR(16) DEFAULT NULL COMMENT '0药品1材料',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_drug_spec` (`drug_id`, `drug_spec_packing_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_drug_code` (`drug_code`),
  KEY `idx_drug_name` (`drug_name`(191)),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.44药品材料字典';
/

-- 2.5.58 SPD 药品材料分类
CREATE TABLE IF NOT EXISTS `m_dict_category` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.58' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `his_dict_id` VARCHAR(64) NOT NULL COMMENT '分类字典ID',
  `his_dict_name` VARCHAR(256) DEFAULT NULL COMMENT '分类名称',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_dict_cat` (`his_dict_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_dict_name` (`his_dict_name`(191)),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.58SPD药品材料分类';
/

-- 2.5.62 SPD 供应商
CREATE TABLE IF NOT EXISTS `m_supplier` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.62' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `supplier_id` VARCHAR(64) NOT NULL COMMENT '供应商ID',
  `supplier_name` VARCHAR(500) DEFAULT NULL COMMENT '供应商名称',
  `input_code` VARCHAR(128) DEFAULT NULL COMMENT '拼音码',
  `full_code` VARCHAR(256) DEFAULT NULL COMMENT '全拼',
  `wb_code` VARCHAR(64) DEFAULT NULL COMMENT '五笔码',
  `order_no` VARCHAR(32) DEFAULT NULL COMMENT '排序号',
  `invalid_flag` VARCHAR(16) DEFAULT NULL COMMENT '作废标志',
  `supplier_code` VARCHAR(128) DEFAULT NULL COMMENT '供应商编码',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '地址',
  `phone` VARCHAR(64) DEFAULT NULL COMMENT '电话',
  `saleman` VARCHAR(128) DEFAULT NULL COMMENT '业务员',
  `saleman_phone` VARCHAR(64) DEFAULT NULL COMMENT '业务员电话',
  `licence` VARCHAR(256) DEFAULT NULL COMMENT '许可证',
  `his_org_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS机构ID',
  `his_creater_id` VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',
  `his_creater_name` VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  `his_create_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS创建时间',
  `his_updater_id` VARCHAR(64) DEFAULT NULL COMMENT '更新人ID',
  `his_update_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS更新时间',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `shipping_addr` VARCHAR(500) DEFAULT NULL COMMENT '发货地址',
  `social_credit_code` VARCHAR(64) DEFAULT NULL COMMENT '统一社会信用代码',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_supplier` (`supplier_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_supplier_name` (`supplier_name`(191)),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.62SPD供应商';
/

-- 2.5.63 SPD 生产厂商
CREATE TABLE IF NOT EXISTS `m_producer` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.63' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `producer_id` VARCHAR(64) NOT NULL COMMENT '生产厂商ID',
  `producer_cnname` VARCHAR(500) DEFAULT NULL COMMENT '中文名',
  `producer_enname` VARCHAR(500) DEFAULT NULL COMMENT '英文名',
  `producer_code` VARCHAR(128) DEFAULT NULL COMMENT '厂商编码',
  `input_code` VARCHAR(128) DEFAULT NULL COMMENT '拼音码',
  `full_code` VARCHAR(256) DEFAULT NULL COMMENT '全拼',
  `wb_code` VARCHAR(64) DEFAULT NULL COMMENT '五笔码',
  `order_no` VARCHAR(32) DEFAULT NULL COMMENT '排序号',
  `invalid_flag` VARCHAR(16) DEFAULT NULL COMMENT '作废标志',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '地址',
  `phone` VARCHAR(64) DEFAULT NULL COMMENT '电话',
  `his_org_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS机构ID',
  `his_creater_id` VARCHAR(64) DEFAULT NULL COMMENT '创建人ID',
  `his_creater_name` VARCHAR(128) DEFAULT NULL COMMENT '创建人',
  `his_create_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS创建时间',
  `his_updater_id` VARCHAR(64) DEFAULT NULL COMMENT '更新人ID',
  `his_update_time` VARCHAR(32) DEFAULT NULL COMMENT 'HIS更新时间',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `producer_type` VARCHAR(16) DEFAULT NULL COMMENT '厂商类型',
  `mah_id` VARCHAR(64) DEFAULT NULL COMMENT '上市许可持有人ID',
  `mah_name` VARCHAR(500) DEFAULT NULL COMMENT '上市许可持有人',
  `social_credit_code` VARCHAR(64) DEFAULT NULL COMMENT '统一社会信用代码',
  `vs_status` VARCHAR(32) DEFAULT NULL COMMENT '对照状态',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_producer` (`producer_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_producer_name` (`producer_cnname`(191)),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.63SPD生产厂商';
/

-- 2.5.82 SPD 合并库存
CREATE TABLE IF NOT EXISTS `m_merge_stock` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.82' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'api' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `dept_id` VARCHAR(64) DEFAULT NULL COMMENT '库存科室ID',
  `dept_code` VARCHAR(64) DEFAULT NULL COMMENT '科室编号',
  `dept_name` VARCHAR(200) DEFAULT NULL COMMENT '科室名称',
  `drug_id` VARCHAR(64) DEFAULT NULL COMMENT '药品/材料ID',
  `drug_code` VARCHAR(128) DEFAULT NULL COMMENT '药品编码',
  `drug_name` VARCHAR(500) DEFAULT NULL COMMENT '药品名称',
  `drug_spec_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '规格包装ID',
  `yc_stock_query_id` VARCHAR(64) DEFAULT NULL COMMENT '合并库存ID',
  `stock_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '库存数量',
  `buy_price` DECIMAL(18,4) DEFAULT NULL COMMENT '进价',
  `retail_price` DECIMAL(18,4) DEFAULT NULL COMMENT '零售价',
  `spec` VARCHAR(500) DEFAULT NULL COMMENT '规格描述',
  `category_id` VARCHAR(64) DEFAULT NULL COMMENT '药品分类ID',
  `category_name` VARCHAR(200) DEFAULT NULL COMMENT '药品分类名称',
  `producer_id` VARCHAR(64) DEFAULT NULL COMMENT '生产厂商ID',
  `producer_name` VARCHAR(500) DEFAULT NULL COMMENT '生产厂商名称',
  `min_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '最小包装单位ID',
  `min_packing_name` VARCHAR(64) DEFAULT NULL COMMENT '最小包装单位名称',
  `packing_id` VARCHAR(64) DEFAULT NULL COMMENT '当前包装单位ID',
  `packing_name` VARCHAR(64) DEFAULT NULL COMMENT '当前包装单位名称',
  `spec_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '规格包装单位ID',
  `spec_packing_name` VARCHAR(64) DEFAULT NULL COMMENT '规格包装单位名称',
  `invalid_flag` VARCHAR(16) DEFAULT NULL COMMENT '停用标识0否1是',
  `occupy_quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '占用数量',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_merge_stock` (`dept_id`, `drug_id`, `drug_spec_packing_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_drug_id` (`drug_id`),
  KEY `idx_yc_stock_query` (`yc_stock_query_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.82SPD合并库存';
/

-- 2.5.43 药房批次库存
CREATE TABLE IF NOT EXISTS `m_drug_batch_stock` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.43' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'api' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `dept_id` VARCHAR(64) DEFAULT NULL COMMENT '药房科室ID',
  `drug_id` VARCHAR(64) DEFAULT NULL COMMENT '药品/材料ID',
  `drug_spec_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '规格包装ID',
  `batch_number` VARCHAR(128) DEFAULT NULL COMMENT '批号',
  `stock_id` VARCHAR(64) DEFAULT NULL COMMENT '库存ID',
  `pharmacy_stock_id` VARCHAR(64) DEFAULT NULL COMMENT '2.5.43 pharmacyStockId',
  `quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '库存数量',
  `stock_amount` DECIMAL(18,4) DEFAULT NULL COMMENT '2.5.43 stockAmount',
  `yc_stock_query_id` VARCHAR(64) DEFAULT NULL COMMENT '2.5.43 ycStockQueryId',
  `buy_price` DECIMAL(18,4) DEFAULT NULL COMMENT '进价',
  `retail_price` DECIMAL(18,4) DEFAULT NULL COMMENT '零售价',
  `effective` VARCHAR(32) DEFAULT NULL COMMENT '有效期',
  `produce_date` VARCHAR(32) DEFAULT NULL COMMENT '生产日期',
  `producer_id` VARCHAR(64) DEFAULT NULL COMMENT '生产厂商ID',
  `producer_name` VARCHAR(500) DEFAULT NULL COMMENT '生产厂商',
  `supplier_id` VARCHAR(64) DEFAULT NULL COMMENT '供应商ID',
  `supplier_name` VARCHAR(500) DEFAULT NULL COMMENT '供应商',
  `packing_id` VARCHAR(64) DEFAULT NULL COMMENT '包装ID',
  `packing_name` VARCHAR(64) DEFAULT NULL COMMENT '包装单位',
  `hospital_id` VARCHAR(64) DEFAULT NULL COMMENT '医院ID',
  `org_id` VARCHAR(64) DEFAULT NULL COMMENT '机构ID',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_batch_stock` (`dept_id`, `drug_id`, `drug_spec_packing_id`, `batch_number`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_drug_id` (`drug_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.43药房批次库存';
/

-- 2.5.102 一级库入退库记录（主表 + 明细）
CREATE TABLE IF NOT EXISTS `m_yk_instock` (
  `mirror_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `api_code` VARCHAR(32) NOT NULL DEFAULT '2.5.102' COMMENT '接口编号',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `request_params_json` TEXT COMMENT '请求入参JSON',
  `raw_item_json` MEDIUMTEXT COMMENT '原始行JSON备份',
  `mirror_source` VARCHAR(32) DEFAULT 'manual_probe' COMMENT '镜像来源',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `instock_code` VARCHAR(128) DEFAULT NULL COMMENT '入退库单号',
  `storage_instock_id` VARCHAR(64) NOT NULL COMMENT '入库单ID',
  `type` VARCHAR(16) DEFAULT NULL COMMENT '0入库1退库',
  `supplier_name` VARCHAR(500) DEFAULT NULL COMMENT '供应商名称',
  `supplier_id` VARCHAR(64) DEFAULT NULL COMMENT '供应商ID',
  `instock_time` VARCHAR(32) DEFAULT NULL COMMENT '入退库时间',
  `record_user_sys_name` VARCHAR(128) DEFAULT NULL COMMENT '记录人',
  `his_creater_name` VARCHAR(128) DEFAULT NULL COMMENT 'HIS创建人',
  `dept_id` VARCHAR(64) DEFAULT NULL COMMENT '科室ID',
  `dept_name` VARCHAR(200) DEFAULT NULL COMMENT '科室名称',
  PRIMARY KEY (`mirror_id`),
  UNIQUE KEY `uk_yk_instock` (`storage_instock_id`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_instock_code` (`instock_code`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.102一级库入退库主表';
/

CREATE TABLE IF NOT EXISTS `m_yk_instock_detail` (
  `detail_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7（36位）',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID，枣强=zaoqiang-tcm-001',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `sync_batch_no` VARCHAR(64) DEFAULT NULL COMMENT '同步批次号',
  `storage_instock_id` VARCHAR(64) NOT NULL COMMENT '入库单ID',
  `instock_code` VARCHAR(128) DEFAULT NULL COMMENT '入退库单号',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `drug_id` VARCHAR(64) DEFAULT NULL COMMENT '药品/材料ID',
  `drug_name` VARCHAR(500) DEFAULT NULL COMMENT '名称',
  `batch_number` VARCHAR(128) DEFAULT NULL COMMENT '批号',
  `spec` VARCHAR(500) DEFAULT NULL COMMENT '规格',
  `effective` VARCHAR(32) DEFAULT NULL COMMENT '有效期',
  `produce_date` VARCHAR(32) DEFAULT NULL COMMENT '生产日期',
  `buy_price` DECIMAL(18,4) DEFAULT NULL COMMENT '进价',
  `retail_price` DECIMAL(18,4) DEFAULT NULL COMMENT '零售价',
  `quantity` DECIMAL(18,4) DEFAULT NULL COMMENT '数量',
  `producer_id` VARCHAR(64) DEFAULT NULL COMMENT '生产厂商ID',
  `producer_name` VARCHAR(500) DEFAULT NULL COMMENT '生产厂商',
  `license_number` VARCHAR(128) DEFAULT NULL COMMENT '许可证号',
  `packing_id` VARCHAR(64) DEFAULT NULL COMMENT '包装ID',
  `packing_name` VARCHAR(64) DEFAULT NULL COMMENT '包装单位',
  `drug_spec_packing_id` VARCHAR(64) DEFAULT NULL COMMENT '规格包装ID',
  `national_medical_insurance_code` VARCHAR(128) DEFAULT NULL COMMENT '国家医保编码',
  `material_or_drug` VARCHAR(16) DEFAULT NULL COMMENT '0药品1材料',
  `supplier_id` VARCHAR(64) DEFAULT NULL COMMENT '供应商ID',
  PRIMARY KEY (`detail_id`),
  UNIQUE KEY `uk_instock_line` (`storage_instock_id`, `drug_spec_packing_id`, `batch_number`, `tenant_id`, `active_env`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_drug_id` (`drug_id`),
  KEY `idx_sync_batch` (`sync_batch_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳云健康HIS镜像表-2.5.102一级库入退库明细(stockDetailList)';
/

-- HIS 单据推送日志（SPD 出库/退库推送后查询，评估文档 §6.5）
CREATE TABLE IF NOT EXISTS `m_his_push_log` (
  `log_id` VARCHAR(36) NOT NULL COMMENT '主键UUID7',
  `hospital_key` VARCHAR(64) NOT NULL COMMENT '医院客户键',
  `tenant_id` VARCHAR(64) NOT NULL COMMENT 'SPD租户ID',
  `active_env` VARCHAR(16) NOT NULL DEFAULT 'prod' COMMENT '环境',
  `spd_bill_id` VARCHAR(64) DEFAULT NULL COMMENT 'SPD主单ID',
  `spd_entry_id` VARCHAR(64) DEFAULT NULL COMMENT 'SPD明细ID',
  `bill_no` VARCHAR(64) DEFAULT NULL COMMENT '单号',
  `bill_type` VARCHAR(16) DEFAULT NULL COMMENT '单据类型 201/401',
  `api_code` VARCHAR(16) NOT NULL COMMENT '2.5.41/2.5.42',
  `request_json` MEDIUMTEXT COMMENT '请求报文',
  `response_json` MEDIUMTEXT COMMENT '响应报文',
  `his_trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'HIS traceId',
  `push_status` VARCHAR(16) DEFAULT NULL COMMENT '成功/失败',
  `push_msg` VARCHAR(500) DEFAULT NULL COMMENT '失败原因',
  `insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  PRIMARY KEY (`log_id`),
  KEY `idx_tenant_bill` (`tenant_id`, `spd_bill_id`),
  KEY `idx_bill_no` (`bill_no`),
  KEY `idx_entry` (`spd_entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='【非标准】众阳HIS推送日志';
/
